const {getDrive,getVaultFolderId,findDataFile}=require('./_google');
const {getVideoUserId,requireVideoUser}=require('./_video-auth');
const {isAdmin}=require('./_auth');
const {Readable}=require('stream');
const crypto=require('crypto');
function clean(value){if(Array.isArray(value))return value.map(clean);if(value&&typeof value==='object'){if(value.remoteFileId){const o={...value};delete o.data;const exp=Math.floor(Date.now()/1000)+24*60*60;const secret=process.env.PUBLIC_FILE_SECRET||process.env.SESSION_SECRET;const sig=crypto.createHmac('sha256',secret).update(`${value.remoteFileId}.${exp}`).digest('base64url');o.url=`/api/files?id=${encodeURIComponent(value.remoteFileId)}&exp=${exp}&sig=${sig}`;return o;}const o={};for(const[k,v]of Object.entries(value)){if(k==='password'||k==='clientPassword')continue;o[k]=clean(v);}return o;}return value;}
async function ctx(){const drive=getDrive();const folderId=await getVaultFolderId(drive);const existing=await findDataFile(drive,folderId);let data={version:102,clients:[],budgetClients:[],trash:[],vendors:[],showcase:{},videos:[],videoUsers:[],videoPosts:[],referenceDesigns:[],projects:[],finance:[]};if(existing){const r=await drive.files.get({fileId:existing.id,alt:'media'},{responseType:'json'});data=r.data||data;}return {drive,folderId,existing,data};}
async function write(c){const media={mimeType:'application/json',body:Readable.from([JSON.stringify({...c.data,version:102,updatedAt:new Date().toISOString()})])};if(c.existing)await c.drive.files.update({fileId:c.existing.id,media,fields:'id,name,modifiedTime',supportsAllDrives:true});else await c.drive.files.create({requestBody:{name:'devkansh-vault-data.json',parents:[c.folderId],mimeType:'application/json'},media,fields:'id,name,modifiedTime',supportsAllDrives:true});}
module.exports=async(req,res)=>{try{if(req.method==='GET'){const c=await ctx();return res.status(200).json({videoUsers:(c.data.videoUsers||[]).map(clean),videoPosts:(c.data.videoPosts||[]).map(clean)});}const uid=requireVideoUser(req,res);if(!uid)return;const c=await ctx();const users=Array.isArray(c.data.videoUsers)?c.data.videoUsers:[];const user=users.find(u=>u.id===uid);if(!user)return res.status(401).json({error:'Video profile not found.'});if(req.method==='POST'){let b=req.body;if(typeof b==='string')b=JSON.parse(b);const p=b?.post;if(!p||String(p.userId)!==uid||!p.remoteFileId)return res.status(400).json({error:'Invalid post.'});const post={...p,id:p.id||('vp'+Date.now()+Math.random().toString(36).slice(2,7)),createdAt:p.createdAt||new Date().toISOString()};c.data.videoPosts=Array.isArray(c.data.videoPosts)?c.data.videoPosts:[];c.data.videoPosts.unshift(post);await write(c);return res.status(200).json({ok:true,post:clean(post)});}if(req.method==='PUT'){let b=req.body;if(typeof b==='string')b=JSON.parse(b);if(b?.name!==undefined)user.name=String(b.name).trim()||user.name;if(b?.profilePhoto!==undefined)user.profilePhoto=b.profilePhoto;if(b?.profilePhotoRemoteFileId!==undefined)user.profilePhotoRemoteFileId=b.profilePhotoRemoteFileId;await write(c);return res.status(200).json({ok:true,user:clean(user)});}if(req.method==='DELETE'){const id=String(req.query?.id||'');const posts=Array.isArray(c.data.videoPosts)?c.data.videoPosts:[];const p=posts.find(x=>x.id===id);if(!p||p.userId!==uid)return res.status(404).json({error:'Post not found.'});c.data.videoPosts=posts.filter(x=>x.id!==id);await write(c);return res.status(200).json({ok:true});}return res.status(405).json({error:'Method not allowed'});}catch(err){console.error(err);return res.status(500).json({error:err.message||'Video data operation failed.'});}};
